POST http://localhost:5000/profile/create/
content-type: application/json

{
    "username" : "hub1",
    "firstname" : "hubert",
    "lastname" : "m-d",
    "password" : "banane",
    "avatar" : "BANANA",
    "rooms_joined" : []
}

###

GET http://localhost:5000/profile/private/hub1

###

DELETE http://localhost:5000/profile/hub1

###

GET http://localhost:5000/profile/stats/x

###

GET http://localhost:5000/profile/rank/4/0